name: El Report 
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart
      - name: Cypress test report
        uses: actions/upload-artifact@v4
        with:
          name: EL SHeport
          path: cypress/reports/html # or path/to/artifact  